ユーザー一覧作成
abeshi03/hc-test pull request #3
Opened 2024-02-09 08:15 UTC by saki-pg

2024-02-09 08:29 UTC, saki-pg commented
## チケットurl
backlog url
[https://haircamp.backlog.com/view/HAIRCAMP_REPLACE-1757](url)

## 概要

ユーザー一覧のUI実装
トップページにユーザー一覧ページへの同線のボタンの追加

## レビューしてほしいポイント

ユーザー画面表示
cssで display: gridで並び替えできると考えましたが、縦一列になってしまい改善できませんでした。

## 検証動画

https://github.com/abeshi03/hc-test/assets/115139489/9de16185-90df-4e06-be36-e074ab6f2f27

--

よろしくお願いいたします。

2024-02-12 08:27 UTC, abeshi03 requested changes
@saki-pg 

コメントしました〜👍
最初なのでかなり細かく指摘入れています！

ご確認お願いいたします🙏

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +export default function UsersPage() {
ディレクトリ階層ですが、
実際の現場だとファイル数多くて散らかるので、

/pages/users.tsx
ってよりかは

/pages/users/index.tsx
とかにする方が多いですね！

- pages
  -  users.tsx
  - posts.tsx
  - lives.tsx
  - archives.tsx
  - ... ect // ファイル数が多くなると散らかりやすい


// この法がファイルが増えてきたり、[id]とかになった時に管理しやすい
- pages
  -  users
    - index.tsx
  - posts
    - index.tsx
  - lives
     - index.tsx
  - archives
    - index.tsx

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +}
最終行は末尾の空白を1行開けるようにしましょう！
実際TypeScriptは動くのですが、他の言語はコンパイル時にエラーになる言語もあるので癖付けておくのが習慣になっています！
https://teratail.com/questions/71778


https://qiita.com/tanakahisateru/items/66359b6217e7ac728856
intelliJを使う時は設定しておけば普段は意識しなくて済みます！

2024-02-12 08:27 UTC, abeshi03 commented on src/components/UserCard/index.tsx
> +interface UserCardProps {
4点です。

- mockでも使うことが予想されるので、types/User.tsのファイルを作って移行させましょう！
- 実際のHAIRCAMPの開発だとinterfaceはほとんど使っておらずtypeを使用しております。こちらも併せてtypeに直しましょうか！
- 風習的にid: stringも一応入れておきましょう！
- Userはpropsの型というより、User型で定義していた方が良さそうです。

```
export type User = {
   ... 型を書く
}

type Props = {
   user: User
}
```

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +const users = [
types/User.ts
に型定義を作ってexportしたら、こちらに

```
const users: User[] = [
  ... 
]
```

と型定義が追加できるはずです！
今の状態だと

```
{ id: 3, name: 'ユーザー3, age: 18' },
```

が入ったらエラーになりませんが、User[]としたら型エラーが出るようになり安全になります🙆‍♂️

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +  { id: 3, name: 'ユーザー3' },
今回はESLintが入っていないので、エラーが出ませんが、
ダブルクウォーテーションととシングルクウォーテーションンが混在しているのでダブルクウォーテーションにあわせましょうか！


調べたら出てくると思うので、ESLintにダブルクウォーテーションではないとエラーを投げるようにeslintrc.jsonに設定の追加をお願いいたします。

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +      <div className={s.cardContainer}>
横並びにならないのはスタイルの問題ですね！
こちらの参照しているCSSファイルは
import s from "./style.module.sass"
ですが

.cardContainer
の記述がありません。

UserCard/style.module.sassに書かれているみたいですね👀

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +      <div className={s.links}>
こちらのdevタグですが、特に必要なさそうです。

Linkに直接スタイルをつければやりたいことは実現できそうです！

```
<Link className={s.link} href="/">ホーム画面へ</Link>
.link
  display: inline-block
  margin-top: 20px
```

2024-02-12 08:27 UTC, abeshi03 commented on src/components/UserCard/style.module.sass
> +  width: 100px
子コンポーネントにwidthやheightをつけるのはNGです！🫨

components/配下は基本的にどこから呼ばれるか事前に知ってはいけません！
今回であれば、UserCardは/usersからしか呼ばれないですが、ページが増えてくると
トップページから呼ばれる可能性もあればユーザー詳細ページでも表示したいということがあります。

この時、子コンポーネント側から大きさが指定されていると、どこからもこの大きさでしか呼び出せないんですよね〜
なので子側にはスタイルを指定しないで、親側に指定してあげることでコンポーネントの流用性が上がります！


```
// ユーザー一覧ページ
<UserCard classNames={s.parent} />

.parent
  width: 100px
  height: 100px

// トップページページ
<UserCard classNames={s.parent} />

.parent
  width: 200px
  height: 200px

// ユーザー詳細ページ
<UserCard classNames={s.parent} />

.parent
  width: 300px
  height: 300px


// 親側で指定すれば、ページごとに大きさが指定できる
```


厳密に言うと、コンポーネント内でwidthとかを指定しておく場合もあるといえばあるのですが、
今回の場合はいらなそうです🙆‍♂️

2024-02-12 08:27 UTC, abeshi03 commented on src/components/UserCard/style.module.sass
> +  border: none
こちらなくてもスタイル変わらないようなので削除で良さそうです！

2024-02-12 08:27 UTC, abeshi03 commented on src/pages/users.tsx
> +        {users.map(user => (
見出しが抜けていそうです👀

<img width="1440" alt="スクリーンショット 2024-02-12 17 22 44" src="https://github.com/abeshi03/hc-test/assets/67625513/c3f58e10-6766-420c-bb10-259da2953899">

2024-02-12 08:27 UTC, abeshi03 commented on src/components/UserCard/index.tsx
> +          height={80}
こちらは100ですね！

<img width="1440" alt="スクリーンショット 2024-02-12 17 23 44" src="https://github.com/abeshi03/hc-test/assets/67625513/a9ab5b1f-e64a-413f-b943-9185bba2ed91">

2024-02-12 08:27 UTC, abeshi03 commented on src/components/UserCard/index.tsx
> +        <h2>{user.name}</h2>
2点です！

- h2タグは見出しに相当するタグで、ユーザーの名前を見出して使ってしまうと、ユーザー一覧では見出しが複数並んでしまうことになります。この場合はdivタグで問題なさそうです👍
- marginがありそうですね👀

<img width="1440" alt="スクリーンショット 2024-02-12 17 25 08" src="https://github.com/abeshi03/hc-test/assets/67625513/d0282c52-3845-472d-8ca5-c7ac272a5fd2">

2024-02-13 00:53 UTC, saki-pg commented
@abeshi03 

レビューいただきましてありがとうございます！！
修正させていただきます🙇🏻‍♀️

2024-02-13 04:35 UTC, saki-pg commented on src/pages/users.tsx
> +export default function UsersPage() {
/pages/users/index.tsx
に修正いたしました！

2024-02-13 04:36 UTC, saki-pg commented on src/pages/users.tsx
> +}
承知いたしました🙇🏻‍♀️

2024-02-13 04:38 UTC, saki-pg commented on src/components/UserCard/index.tsx
> +interface UserCardProps {
4点修正いたしました！

2024-02-13 04:40 UTC, saki-pg commented on src/pages/users.tsx
> +const users = [
User[]に修正いたしました🙋🏻‍♀️

2024-02-13 04:41 UTC, saki-pg commented on src/pages/users.tsx
> +  { id: 3, name: 'ユーザー3' },
承知いたしました🙇🏻‍♀️
eslintrc.jsonに設定追加をいたしました。

2024-02-13 04:45 UTC, saki-pg commented on src/pages/users.tsx
> +      <div className={s.cardContainer}>
記述が間違えていたのを修正いたしました！

2024-02-13 04:49 UTC, saki-pg commented on src/pages/users.tsx
> +      <div className={s.links}>
Link の記述を修正いたしました！

2024-02-13 05:13 UTC, saki-pg commented on src/components/UserCard/style.module.sass
> +  border: none
<img width="851" alt="コンソール" src="https://github.com/abeshi03/hc-test/assets/115139489/3061afd9-3d99-4c16-9004-57ffd5a9abb4">

 スタイル適用がない部分を削除いたしました！
 justify-content: center
 border: none

2024-02-13 05:16 UTC, saki-pg commented on src/pages/users.tsx
> +        {users.map(user => (
見出しを追加いたしました🙇🏻‍♀️

2024-02-13 05:16 UTC, saki-pg commented on src/components/UserCard/index.tsx
> +          height={80}
サイズを100に修正いたしました！

2024-02-13 05:19 UTC, saki-pg commented on src/components/UserCard/index.tsx
> +        <h2>{user.name}</h2>
divタグ修正、margin追加を
いたしました！

2024-02-13 05:38 UTC, saki-pg commented on src/components/UserCard/style.module.sass
> +  width: 100px
承知いたしました！

子コンポーネントの
width　height
を削除いたしました。

2024-02-13 06:13 UTC, abeshi03 requested changes
かなりよくなりました！🎉
細かい部分コメントしましたのでご確認お願いします！

2024-02-13 06:13 UTC, abeshi03 commented on .eslintrc.json
> +    "quotes": ["error", "double"]
👍

2024-02-13 06:13 UTC, abeshi03 commented on src/pages/style.module.sass
> +.link
.sassファイルに書くクラスとjsx側に書くクラスは同じ順番にしましょう！


```
<Layout>
      <h2 className={s.title}>ユーザー一覧</h2>
      <div className={s.cardContainer}>
        {users.map(user => (
          <UserCard 
            key={user.id}
            user={user}
          />
        ))}
      </div>
      <Link className={s.link} href="/">ホーム画面へ</Link>
    </Layout>
```

こうなっているので、

```
.title
  ... 

.cardContainer
  ... 

.link
  ... 
```

のようになっていると第三者から見て見通しの良いコードになります👍

.linksは使われ無くなっているので削除しましょう！！

2024-02-13 06:13 UTC, abeshi03 commented on src/types/User.ts
> +export type User = {
👍

2024-02-13 06:19 UTC, saki-pg commented on src/pages/style.module.sass
> +.link
承知いたしました！

.sassファイル順番修正
.links削除
いたしました！

2024-02-13 06:21 UTC, saki-pg commented
ありがとうございます！！
修正いたします！

2024-02-13 06:52 UTC, abeshi03 approved these changes
![LGTM](https://images.lgtmgen.org/02297748-08c4-4ecc-8589-085cb55abd93)

2024-02-13 07:27 UTC, merged