jsonplaceholderからユーザー情報を取得
abeshi03/hc-test pull request #4
Opened 2024-02-13 09:40 UTC by saki-pg

2024-02-13 09:57 UTC, saki-pg commented
## チケットurl

https://haircamp.backlog.com/view/HAIRCAMP_REPLACE-1757#comment-345177272


## 概要

Userの型をjsonplaceholderのUser型に直す
react-queryを用いて、jsonplaceholderからユーザー情報を取得


## レビューしてほしいポイント

User型と、jsonplaceholderからのユーザー情報取得記述のレビューをお願いしたいです！


## 検証動画

https://github.com/abeshi03/hc-test/assets/115139489/dee78f44-70ac-43b8-82e5-6818f082b9bc


---

よろしくお願いいたします！

2024-02-13 10:26 UTC, abeshi03 requested changes
@saki-pg 

いくつかコメントしましたー🙋
ご確認ください！

2024-02-13 10:26 UTC, abeshi03 commented on src/pages/_app.tsx
> +    <QueryClientProvider client={queryClient}>
👍

2024-02-13 10:26 UTC, abeshi03 commented on package.json
> +    "axios": "^1.6.7",
ライブラリーのバージョンはなるべく固定してinstallしましょう！

"axios": "^1.6.7" ...  これはaxios パッケージのバージョン 1.6.7 またはそれ以降のバージョンを使用することを意味します。メジャーバージョン（最初の数字）は 1 のまま変わらないことを指示しています。つまり、1.6.7、1.7.0、1.8.0 などは許容されますが、2.0.0 は含まれません。


"axios": "1.6.7" ... 逆にこれは1.6.7のバージョンを使用する。ということになります！

バージョンの幅が広いと、ライブラリーのバージョンが上がった際に依存関係が崩れて、バグを引き起こすみたいなこともチラホラ起きたりします。

そのため、基本的に自分でinstallするバージョンは固定することを心がけましょう！
ライブラリーをinstallする際は-Eオプションをつけましょう！

-Eオプションをつけると簡単に固定できます👍

```
npm i -E axios

npm i -E react-query
```

再度実行すれば固定されると思うので試してみてください🙆‍♂️

2024-02-13 10:26 UTC, abeshi03 commented on src/pages/users/index.tsx
> +const fetchUsers = async () => {
せっかくなので型定義しましょう！

<img width="1440" alt="スクリーンショット 2024-02-13 19 07 45" src="https://github.com/abeshi03/hc-test/assets/67625513/3c7aa79b-6cb8-4056-9e28-ae57ac2ca4f1">

現状この関数はPromise<any>を返しています。
anyになっているので、Promiseが何を返してもTypeScriptはエラーを返すことはありません。

```
// 非同期処理なのでPromiseを返す ... PromiseはUser[]を返す
const fetchUsers = async (): Promise<User[]> => {
  // axiosもジェネリクスで型定義できます！
  const res = await axios.get<User[]>("https://jsonplaceholder.typicode.com/users");
  return res.data;
}
```

参考
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise

2024-02-13 10:26 UTC, abeshi03 commented on src/pages/users/index.tsx
> +const { data: users = [], isLoading } = useQuery<User[]>(["users"], fetchUsers);
インデントずれているので揃えましょう！

2024-02-13 10:26 UTC, abeshi03 commented on src/pages/users/index.tsx
> +if (isLoading) return <Spinner />;
こちらですが、ユーザー体験としては少しよろしくない状態になっています👀

今の状態だと、

```
  // ローディング中はSpinner
  if (isLoading) return <Spinner />;

  // ローディング完了したら見出しやヘッダー、ユーザーリストを表示
  return (
    <Layout>
      <h2 className={s.title}>ユーザー一覧</h2>
      <div className={s.cardContainer}>
        {users.map(user => (
          <UserCard
            key={user.id}
            user={user}
          />
        ))}
      </div>
      <Link className={s.link} href="/">ホーム画面へ</Link>
    </Layout>
  );
```

という感じになっています。

https://github.com/abeshi03/hc-test/assets/67625513/51d4362a-22b7-4f45-9387-95b3efe8a50e


ただ実際に、データを取得しているのはユーザーのリストだけなんですよね〜🤔

このような場合は、

- 見出しやヘッダーは先に見せる
- ユーザーリストのみ、ローディングを挟む

とした方が良いです！

https://github.com/abeshi03/hc-test/assets/67625513/b7ed706d-242f-450f-a1ec-f91090d3a5b2

これであれば、ユーザーはローディング中でも
- ユーザー一覧の見出しが出ているので何が表示されるか想像がつきやすい
- ネットワークの都合でユーザー一覧の取得が遅くてもヘッダーで他の画面に遷移できる
等のメリットが出てきます。


Udemyとか見てみるとわかりやすいですが、この画面だと、ここに次のコースのおすすめが表示されると言うことが直感的に理解しやすいですね👀

https://github.com/abeshi03/hc-test/assets/67625513/ba0427d0-dcd1-458b-b558-b1d9ffd4bf4f

こちらは関数に切り出してあげると実現できます！

```
const displayUsers = () => {
    if (isLoading) return <Spinner />;

    return (
      <div className={s.cardContainer}>
        {users.map(user => (
          <UserCard
            key={user.id}
            user={user}
          />
        ))}
      </div>
    )
  }

  return (
    <Layout>
      <h2 className={s.title}>ユーザー一覧</h2>
      {displayUsers()}
      <Link className={s.link} href="/">ホーム画面へ</Link>
    </Layout>
  );
```

2024-02-14 01:15 UTC, saki-pg commented on package.json
> +    "axios": "^1.6.7",
-Eオプションをつけて、コマンド実行いたしました🙋🏻‍♀️

2024-02-14 01:38 UTC, saki-pg commented on src/pages/users/index.tsx
> +const fetchUsers = async () => {
型定義いたしました！

2024-02-14 01:39 UTC, saki-pg commented on src/pages/users/index.tsx
> +const { data: users = [], isLoading } = useQuery<User[]>(["users"], fetchUsers);
インデントのずれを修正いたしました！

2024-02-14 01:50 UTC, saki-pg commented on src/pages/users/index.tsx
> +if (isLoading) return <Spinner />;
承知いたしました！
全体がローディングになっていたのを、ユーザーのみローディングの記述に修正いたしました！

2024-02-14 01:54 UTC, saki-pg commented
@abeshi03 

レビューいただいた箇所を修正いたしました！
よろしくお願いいたします！

2024-02-14 02:01 UTC, abeshi03 approved these changes
![LGTM](https://images.lgtmgen.org/0c590479-dab6-4451-bf02-23546b991d99)
バッチリです👍

2024-02-14 02:01 UTC, abeshi03 commented on package.json
> +    "react-query": "3.39.3",
👍

2024-02-14 02:15 UTC, merged